# Generated by Django 3.2.18 on 2023-04-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0030_resourcelog_base_resour_appname_298cbc_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApimsCasierJudiciaireConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Identifier')),
                ('description', models.TextField(verbose_name='Description')),
                ('users', models.ManyToManyField(blank=True, related_name='_passerelle_imio_apims_casier_judiciaire_apimscasierjudiciaireconnector_users_+', related_query_name='+', to='base.ApiUser')),
            ],
            options={
                'verbose_name': 'Connecteur APIMS Casier Judiciaire',
            },
        ),
    ]
