# Generated by Django 3.2.18 on 2023-04-17 14:11

from django.db import migrations, models
import passerelle_imio_apims_casier_judiciaire.models


class Migration(migrations.Migration):

    dependencies = [
        ('passerelle_imio_apims_casier_judiciaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimscasierjudiciaireconnector',
            name='municipality_nis_code',
            field=models.CharField(blank=True, help_text="Token d'identification de l'organisme dans APIMS Casier Judiciaire", max_length=128, verbose_name="Token d'identification"),
        ),
        migrations.AddField(
            model_name='apimscasierjudiciaireconnector',
            name='password',
            field=models.CharField(blank=True, help_text='Mot de passe APIMS Casier Judiciaire', max_length=128, verbose_name='Mot de passe'),
        ),
        migrations.AddField(
            model_name='apimscasierjudiciaireconnector',
            name='url',
            field=models.URLField(blank=True, default='https://api-staging.imio.be/bosa/v1', help_text='URL de APIMS Casier Judiciaire', max_length=128, validators=[passerelle_imio_apims_casier_judiciaire.models.validate_url], verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='apimscasierjudiciaireconnector',
            name='username',
            field=models.CharField(blank=True, help_text='Utilisateur APIMS Casier Judiciaire', max_length=128, verbose_name='Utilisateur'),
        ),
    ]
